[package]
name = "day18p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
num-integer = "0.1.44"
serde = { version = "1.0.132", features = [ "derive" ] }
serde_json = "1.0.73"
